// <auto-generated />
using System;
using Domain.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250330133202_RemoveMangaIdFromFeaturedCollectionPermission")]
    partial class RemoveMangaIdFromFeaturedCollectionPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuthMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("AccessTokenExpiration")
                        .HasColumnType("datetime");

                    b.Property<string>("AuthId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AuthType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__AuthMeth__3214EC078CF7B1CD");

                    b.HasIndex("UserId");

                    b.ToTable("AuthMethods");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool?>("HasComment")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasDraft")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NovelContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("StatusChapter")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImage")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Chapters__3214EC07F52585A5");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Domain.Entities.ChapterImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FileSize")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ChapterI__3214EC07E2B6F532");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("ChapterImages");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("bit");

                    b.Property<long?>("MangaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3214EC07CE8527B9");

                    b.HasIndex("ChapterId");

                    b.HasIndex("MangaId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Entities.CommentReaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__CommentR__3214EC072CADC68D");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPublish")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Featured__3214EC0736CEA38B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("FeaturedCollections");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollectionManga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FeaturedCollectionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MangaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Featured__3214EC07A35C926C");

                    b.HasIndex("FeaturedCollectionId");

                    b.HasIndex("MangaId");

                    b.ToTable("FeaturedCollectionMangas");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollectionPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("FeaturedCollectionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MangaId")
                        .HasColumnType("bigint");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Featured__3214EC07DA4FFC3C");

                    b.HasIndex("FeaturedCollectionId");

                    b.HasIndex("MangaId");

                    b.HasIndex("UserId");

                    b.ToTable("FeaturedCollectionPermissions");
                });

            modelBuilder.Entity("Domain.Entities.Genere", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Generes__3214EC07C42CC74C");

                    b.ToTable("Generes");
                });

            modelBuilder.Entity("Domain.Entities.Manga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("Artist")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("Format")
                        .HasColumnType("int");

                    b.Property<bool?>("HasAdult")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Preface")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("Publishor")
                        .HasColumnType("bigint");

                    b.Property<int?>("Region")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseStatus")
                        .HasColumnType("int");

                    b.Property<long?>("SubAuthor")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("Translator")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Mangas__3214EC07903C34BB");

                    b.HasIndex("Artist");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Publishor");

                    b.HasIndex("SubAuthor");

                    b.HasIndex("Translator");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("Domain.Entities.MangaGenre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MangaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__MangaGen__3214EC077172674E");

                    b.HasIndex("GenreId");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaGenres");
                });

            modelBuilder.Entity("Domain.Entities.MangaInteraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChapterId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("InteractionType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MangaId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__MangaInt__3214EC075D87671E");

                    b.HasIndex("ChapterId");

                    b.HasIndex("MangaId");

                    b.HasIndex("UserId");

                    b.ToTable("MangaInteractions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07CE933FCB");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0768201A46");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053495D01949")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.AuthMethod", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("AuthMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__AuthMetho__UserI__49C3F6B7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ChapterCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Chapters__Create__22751F6C");

                    b.HasOne("Domain.Entities.User", "ModifiedByNavigation")
                        .WithMany("ChapterModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Chapters__Modifi__236943A5");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("Domain.Entities.ChapterImage", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("ChapterImages")
                        .HasForeignKey("ChapterId")
                        .HasConstraintName("FK__ChapterIm__Chapt__2A164134");

                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ChapterImageCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__ChapterIm__Creat__282DF8C2");

                    b.HasOne("Domain.Entities.User", "ModifiedByNavigation")
                        .WithMany("ChapterImageModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__ChapterIm__Modif__29221CFB");

                    b.Navigation("Chapter");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("Comments")
                        .HasForeignKey("ChapterId")
                        .HasConstraintName("FK_Comments_ChapterId");

                    b.HasOne("Domain.Entities.Manga", "Manga")
                        .WithMany("Comments")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Comments__MangaI__0E6E26BF");

                    b.HasOne("Domain.Entities.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK__Comments__Parent__0F624AF8");

                    b.Navigation("Chapter");

                    b.Navigation("Manga");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Domain.Entities.CommentReaction", b =>
                {
                    b.HasOne("Domain.Entities.Comment", "Comment")
                        .WithMany("CommentReactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CommentRe__Comme__14270015");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("CommentReactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CommentRe__UserI__151B244E");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollection", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("FeaturedCollectionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__FeaturedC__Creat__6754599E");

                    b.HasOne("Domain.Entities.User", "ModifiedByNavigation")
                        .WithMany("FeaturedCollectionModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__FeaturedC__Modif__68487DD7");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollectionManga", b =>
                {
                    b.HasOne("Domain.Entities.FeaturedCollection", "FeaturedCollection")
                        .WithMany("FeaturedCollectionMangas")
                        .HasForeignKey("FeaturedCollectionId")
                        .IsRequired()
                        .HasConstraintName("FK__FeaturedC__Featu__6EF57B66");

                    b.HasOne("Domain.Entities.Manga", "Manga")
                        .WithMany("FeaturedCollectionMangas")
                        .HasForeignKey("MangaId")
                        .IsRequired()
                        .HasConstraintName("FK__FeaturedC__Manga__6E01572D");

                    b.Navigation("FeaturedCollection");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollectionPermission", b =>
                {
                    b.HasOne("Domain.Entities.FeaturedCollection", "FeaturedCollection")
                        .WithMany("FeaturedCollectionPermissions")
                        .HasForeignKey("FeaturedCollectionId")
                        .HasConstraintName("FK__FeaturedC__Featu__6D0D32F4");

                    b.HasOne("Domain.Entities.Manga", null)
                        .WithMany("FeaturedCollectionPermissions")
                        .HasForeignKey("MangaId");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("FeaturedCollectionPermissions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__FeaturedC__UserI__6C190EBB");

                    b.Navigation("FeaturedCollection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Manga", b =>
                {
                    b.HasOne("Domain.Entities.User", "ArtistNavigation")
                        .WithMany("MangaArtistNavigations")
                        .HasForeignKey("Artist")
                        .HasConstraintName("FK_Mangas_Artist");

                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("MangaCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Mangas_CreatedBy");

                    b.HasOne("Domain.Entities.User", "ModifiedByNavigation")
                        .WithMany("MangaModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_Mangas_ModifiedBy");

                    b.HasOne("Domain.Entities.User", "PublishorNavigation")
                        .WithMany("MangaPublishorNavigations")
                        .HasForeignKey("Publishor")
                        .HasConstraintName("FK_Mangas_Publishor");

                    b.HasOne("Domain.Entities.User", "SubAuthorNavigation")
                        .WithMany("MangaSubAuthorNavigations")
                        .HasForeignKey("SubAuthor")
                        .HasConstraintName("FK_Mangas_SubAuthor");

                    b.HasOne("Domain.Entities.User", "TranslatorNavigation")
                        .WithMany("MangaTranslatorNavigations")
                        .HasForeignKey("Translator")
                        .HasConstraintName("FK_Mangas_Translator");

                    b.Navigation("ArtistNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("PublishorNavigation");

                    b.Navigation("SubAuthorNavigation");

                    b.Navigation("TranslatorNavigation");
                });

            modelBuilder.Entity("Domain.Entities.MangaGenre", b =>
                {
                    b.HasOne("Domain.Entities.Genere", "Genre")
                        .WithMany("MangaGenres")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("FK__MangaGenr__Genre__60A75C0F");

                    b.HasOne("Domain.Entities.Manga", "Manga")
                        .WithMany("MangaGenres")
                        .HasForeignKey("MangaId")
                        .IsRequired()
                        .HasConstraintName("FK__MangaGenr__Manga__5FB337D6");

                    b.Navigation("Genre");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("Domain.Entities.MangaInteraction", b =>
                {
                    b.HasOne("Domain.Entities.Chapter", "Chapter")
                        .WithMany("MangaInteractions")
                        .HasForeignKey("ChapterId")
                        .HasConstraintName("FK__MangaInte__Chapt__32AB8735");

                    b.HasOne("Domain.Entities.Manga", "Manga")
                        .WithMany("MangaInteractions")
                        .HasForeignKey("MangaId")
                        .HasConstraintName("FK__MangaInte__Manga__31B762FC");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("MangaInteractions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__MangaInte__UserI__30C33EC3");

                    b.Navigation("Chapter");

                    b.Navigation("Manga");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__4222D4EF");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Chapter", b =>
                {
                    b.Navigation("ChapterImages");

                    b.Navigation("Comments");

                    b.Navigation("MangaInteractions");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentReactions");

                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("Domain.Entities.FeaturedCollection", b =>
                {
                    b.Navigation("FeaturedCollectionMangas");

                    b.Navigation("FeaturedCollectionPermissions");
                });

            modelBuilder.Entity("Domain.Entities.Genere", b =>
                {
                    b.Navigation("MangaGenres");
                });

            modelBuilder.Entity("Domain.Entities.Manga", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FeaturedCollectionMangas");

                    b.Navigation("FeaturedCollectionPermissions");

                    b.Navigation("MangaGenres");

                    b.Navigation("MangaInteractions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuthMethods");

                    b.Navigation("ChapterCreatedByNavigations");

                    b.Navigation("ChapterImageCreatedByNavigations");

                    b.Navigation("ChapterImageModifiedByNavigations");

                    b.Navigation("ChapterModifiedByNavigations");

                    b.Navigation("CommentReactions");

                    b.Navigation("FeaturedCollectionCreatedByNavigations");

                    b.Navigation("FeaturedCollectionModifiedByNavigations");

                    b.Navigation("FeaturedCollectionPermissions");

                    b.Navigation("MangaArtistNavigations");

                    b.Navigation("MangaCreatedByNavigations");

                    b.Navigation("MangaInteractions");

                    b.Navigation("MangaModifiedByNavigations");

                    b.Navigation("MangaPublishorNavigations");

                    b.Navigation("MangaSubAuthorNavigations");

                    b.Navigation("MangaTranslatorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
